All logging includes trace-id and parent-id at toplevel of log message
jomco/eduhub-rio-mapper pull request #134
Opened 2022-12-29 15:42 UTC by mdemare

2023-01-05 08:51 UTC, joodie requested changes
In `cli/do-async-callback` moet denk ik ook nog de trace-context in de `with-mdc` toegevoegd worden.

2023-01-05 08:51 UTC, joodie commented on src/nl/surf/eduhub_rio_mapper/job.clj
> +                        "upsert" (update! job)))
Deze indentation verandering is raar; alles na 1e argument van `with-context` is body.

2023-01-05 10:49 UTC, mdemare commented
Updated

2023-01-13 08:18 UTC, joodie approved these changes
Prima!

2023-01-13 08:21 UTC, merged