add soap action to logging
jomco/eduhub-rio-mapper pull request #136
Opened 2023-01-05 09:10 UTC by mdemare

- All logging includes trace-id and parent-id at toplevel of log message
- Added token to mdc context for callbacks
- Log soap-action and ooapi-id

2023-01-16 10:59 UTC, joodie requested changes
Kan je deze PR up-to-date maken met de main branch?

Ik denk verder dat het voor logging handiger is om soapaction uit de http headers te vissen en die te loggen in de http-utils ipv overal waar we een soap call opzetten

2023-01-16 14:15 UTC, mdemare commented
Er gebeurt hier meer dan alleen het uitvoeren van de http-call. Het is handig om de soap-action ook in de context te hebben bij andere logging statements, bv. een xsd validatie error.

2023-01-16 14:16 UTC, mdemare commented
Ik heb hem gerebased.

2023-01-19 09:52 UTC, joodie approved these changes

2023-01-19 10:07 UTC, merged