Convert ooapi uuids to lower case.
jomco/eduhub-rio-mapper pull request #169
Opened 2023-03-14 16:26 UTC by mdemare

2023-03-15 10:43 UTC, joodie requested changes
Er zijn toch veel meer UUIDs in de ooapi? Worden die niet verder doorgegeven?

2023-03-15 12:39 UTC, jelmerderonde commented
@joodie er zijn inderdaad veel meer uuids, maar ik denk dat je door deze twee eigenSleutels aan te pakken het probleem misschien al wel opgelost hebt.

2023-03-16 10:20 UTC, joodie approved these changes

2023-03-20 09:27 UTC, remvee approved these changes

2023-03-21 09:08 UTC, merged