Link
jomco/eduhub-rio-mapper pull request #170
Opened 2023-03-15 14:47 UTC by mdemare

2023-03-20 12:34 UTC, remvee requested changes
Do not forget to update CLI.md, doc/design/rio-mapper-ontwerp.org and doc/design/rio-mapper-api.org.

2023-03-21 10:33 UTC, mdemare commented on src/nl/surf/eduhub_rio_mapper/processing.clj
> +              rio-new  (mapv (sleutel-changer new-id finder) rio-obj)
I want a hiccup-style vector, and I want to test for vectorness.

2023-03-21 14:12 UTC, remvee requested changes

2023-03-21 14:12 UTC, remvee commented on src/nl/surf/eduhub_rio_mapper/api.clj
> +      ::rio/opleidingscode rio-code))
Shouldn't this be the following (and why are there no test failing on this):

```clojure
(assoc-in (job-route (assoc-in request [:params :action] link))
          [:job ::rio/opleidinscode]
          rio-code)
```

Btw: proper indentation makes this more readable.

2023-03-27 11:25 UTC, remvee requested changes
This: https://github.com/jomco/eduhub-rio-mapper/pull/170/files#r1143438881

And please document link in API.md.

2023-03-28 13:41 UTC, remvee approved these changes

2023-03-28 14:03 UTC, merged