Resolve throws error unless not found
jomco/eduhub-rio-mapper pull request #177
Opened 2023-03-28 15:23 UTC by mdemare

2023-03-31 09:20 UTC, joodie requested changes

2023-03-31 09:20 UTC, joodie commented on src/nl/surf/eduhub_rio_mapper/rio/loader.clj
> +      (log-rio-action-response (str "RESOLVE NOT FOUND - ID: " id) element)
1. Ik denk dat die HOOFDLETTERS wel uit de logging weg kunnen. De error message moet zowiezo duidelijker.
2. Deze error zou denk ik niet retryable moeten zijn hier; dus `(ex-info  ... {:retryable? false})`
3. Er zit geen test bij.

2023-04-03 09:08 UTC, remvee commented on src/nl/surf/eduhub_rio_mapper/rio/loader.clj
> +      (when-not (= "A01161" (:foutcode foutmelding))
Extract to constant, properly describe error -- "De externe identificatie komt niet voor in RIO" -- and reason to handle it differently.

2023-04-03 11:30 UTC, remvee approved these changes

2023-04-04 08:12 UTC, remvee approved these changes

2023-04-05 08:42 UTC, joodie approved these changes

2023-04-05 08:43 UTC, merged